# Generated by Django 4.2.7 on 2023-12-30 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='reader',
            new_name='account',
        ),
    ]
